[workspace]
members = [
    "runner-reconstruction-update",
    "runner-reconstruction-global",
    "runner-reconstruction-local",
    "runner-reconstruction-local-auki-sdk",
    "bin",
]
resolver = "2"

[workspace.package]
edition = "2021"
publish = false

# Metadata used by scripts/CI; clippy warnings are denied via CI commands.
[workspace.metadata.ci]
deny-warnings = true

[patch.crates-io]
posemesh-compute-node-runner-api = { git = "https://github.com/aukilabs/posemesh.git", rev = "21078e510050a5e62be43018c3d8b2fc01b756e9" }
