##
## Go build for server
##
FROM --platform=$BUILDPLATFORM golang:1.21 AS go-build
RUN mkdir -p /app
WORKDIR /app
ADD server/go /app
ARG TARGETOS
ARG TARGETARCH
ARG VERSION
RUN CGO_ENABLED=0 GOOS="${TARGETOS}" GOARCH="${TARGETARCH}" go build
