reconstruction-server:
  image:
    pullPolicy: Always
    tag: latest
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/group.name: default
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
  resources:
    limits:
      cpu: 8
      memory: 12Gi
      nvidia.com/gpu: 1
    requests:
      cpu: 6
      memory: 6Gi
  tolerations:
    - key: "dedicated"
      value: "karpenterGPU"
      effect: "NoSchedule"
