cluster_eps: 0.2
cluster_min_points: 6
display: false
height_threshold: 1.2
occlusion_method: alphashape_optimized
outlier_min_points: 6
outlier_radius: 0.2
output_dir: ./output/occlusion_box
path: ./path/to/pointcloud.ply
viewpoint_dir: ./view_points
voxel_size: 0.1
xy_plane_clustering: false
debug: true
debug_ply: ''