cluster_eps: 0.4
cluster_min_points: 20
display: false
height_threshold: 0.7
occlusion_method: textured_mesh
alphashape_alpha: 1.0
poisson_depth: 7
outlier_min_points: 10
outlier_radius: 0.3
output_dir: ./output/occlusion_box
path: /path/to/jobs/my_domain_job/refined/global/sam
viewpoint_dir: ./view_points
voxel_size: 0.01
xy_plane_clustering: false
debug: true
debug_ply: ''