cluster_eps: 0.2
cluster_min_points: 6
display: false
height_threshold: -0.6
occlusion_method: alphashape
opengl: true
outlier_min_points: 6
outlier_radius: 0.2
output_dir: ./output/occlusion_box
path: /path/to/jobs/my_domain_job/refined/global/sam
viewpoint_dir: ./view_points
voxel_size: 0.1
xy_plane_clustering: false