name: CI

on:
  push:
    branches:
      - main
      - "feature/**"
      - "bug/**"
      - "chore/**"
      - "hotfix/**"
  pull_request:

jobs:
  checks:
    uses: aukilabs/github-actions/.github/workflows/rust-workflow.yml@v2
    with:
      work_dir: server/rust
      enable_test: true
      enable_build: false
      test_command: |
        cargo fmt --all -- --check
        cargo clippy --workspace --all-targets --all-features -- -D warnings
        cargo test --workspace
