name: Build Docker Image

on:
  push:
    branches:
      - feature/sdk-integration

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Free up space
        run: |
          sudo sudo rm -rf /usr/share/dotnet  # ~20GB
          sudo rm -rf /opt/ghc           # ~4GB
          sudo rm -rf /usr/local/lib/android  # ~10GB

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.GLOBAL_COMMON_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.GLOBAL_COMMON_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.GLOBAL_COMMON_AWS_REGION }}
      
      - name: Log in to AWS ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ steps.ecr-login.outputs.registry }}/reconstruction-server
          tags: |
            type=ref,event=branch
            type=sha,prefix=,format=long

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
