name: Tag Release

concurrency:
  group: reconstruction-server-tag-${{ github.ref_name }}
  cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/') }}

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    uses: aukilabs/github-actions/.github/workflows/rust-workflow.yml@v2
    with:
      # Build multi-arch binaries and push image
      enable_build: true
      work_dir: server/rust
      docker_context: .
      image_name: reconstruction-server
      aws_region: ${{ vars.GLOBAL_COMMON_AWS_REGION }}
      # Enable ArgoCD sync + restart for deployment
      enable_sync: true
      enable_restart: true
      argocd_host: argocd.dev.aukiverse.com
      argocd_app: reconstruction-server
    secrets:
      aws_access_key: ${{ secrets.GLOBAL_COMMON_AWS_ACCESS_KEY }}
      aws_secret_access_key: ${{ secrets.GLOBAL_COMMON_AWS_SECRET_ACCESS_KEY }}
      argocd_password: ${{ secrets.GLOBAL_DEV_ARGOCD_PASSWORD }}
