name: Docker build and push

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build
    runs-on: [self-hosted, Linux]
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update version in file
        run: |
          sed -i 's/VERSION = "develop"/VERSION = "${{ github.ref_name }}"/' utils/data_utils.py

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.GLOBAL_COMMON_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.GLOBAL_COMMON_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.GLOBAL_COMMON_AWS_REGION }}
      - name: Log in to AWS ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker build and push
        id: docker-build-and-push
        run: |

          docker build \
            -t "${{ steps.ecr-login.outputs.registry }}/reconstruction-server:latest" \
            -t "${{ steps.ecr-login.outputs.registry }}/reconstruction-server:${{ github.ref_name }}" \
            --push \
            -f docker/Dockerfile \
            .
